CREATE DATABASE 'ktproject';USE 'ktproject';DROP TABLE IF EXISTS 'cjxj_resource_table';

CREATE TABLE 'cjxj_resource_table' (
  'BZ_NAME' VARCHAR(30) NOT NULL,
  'BZ_INTRODUCE' VARCHAR(1800) DEFAULT NULL,
  'SRC_NAME' VARCHAR(600) NOT NULL,
  'ID' INT(11) NOT NULL AUTO_INCREMENT,
  'BZ_FL' DOUBLE NOT NULL,
  'LINKURL' VARCHAR(1500) NOT NULL,
  'CREATEDATE' TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ('ID')
) ENGINE=INNODB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS 'whkt_resource_table';

CREATE TABLE 'whkt_resource_table' (
  'ID' VARCHAR(150) NOT NULL,
  'IMAGEURL' VARCHAR(150) DEFAULT NULL,
  'TITLE' VARCHAR(100) DEFAULT NULL,
  'CREATEDATE' DATETIME DEFAULT NULL,
  PRIMARY KEY ('ID')
) ENGINE=INNODB DEFAULT CHARSET=utf8;

